### ISSUE TITLE
why is there  not a pv for uptrace instance and clickhouse instance

### ISSUE THREAD

**Issue by sixwaaaay** [uptrace/helm-charts#11]

**Comment by vmihailenco** [comment]
Uptrace helm chart does not come with a clickhouse instance. And starting with v1.4, Uptrace should not write anything to the disk. Before v1.4, you could use PostgreSQL instead of SQLite so a volume is not needed either.

**Comment by vmihailenco** [comment]
It actually looks like we have an optional [ClickHouse instance](https://github.com/uptrace/helm-charts/blob/master/charts/uptrace/values.yaml#L12-L26) so we probably should have a persistent volume as well. I can't really say for sure, but feel free to send a PR.
