### ISSUE TITLE
how/where to specify hostname and multiple projects

### ISSUE THREAD

**Issue by a1git** [uptrace/helm-charts#15]
Hi, 
uptrace is installed using helm as: 
helm install -n uptrace --create-namespace uptrace uptrace/uptrace

ingress is setup on https:// that points to the uptrace service pointing to 14318 ..   the https://uptrace.internal-domain.com works. 

we see only 1 project with 

OTLP/HTTP | http://project2_secret_token@localhost:14318/2

how to add more projects and also change the HTTP endpoint to  to https://uptrace.internal-domain.com/

**Comment by vmihailenco** [comment]
Hello,

Please check these links:
- https://github.com/uptrace/helm-charts#configuration
- https://uptrace.dev/get/config.html#managing-projects
- https://uptrace.dev/get/config.html#tls

https://uptrace.dev/get/config.html#managing-projects
