### ISSUE TITLE
Default chart values include recommended name

### ISSUE THREAD

**Issue by wfhartford** [uptrace/helm-charts#2]
The chart's default values embed the clickhouse address as `clickhouse-my-uptrace:9000`. The `my-uptrace` part is the recommended value for the helm install name, if a user does not use the recommended name, uptrace will fail to start because it cannot connect to clickhouse.

**Comment by wfhartford** [comment]
A workaround for this issue can be applied by editing / specifying the `uptrace.config.ch.addr` value when the helm install command is executed.

**Comment by vmihailenco** [comment]
@wfhartford thanks for bringing this. Do you have any suggestions how this should be addressed?

**Comment by wfhartford** [comment]
Unfortunately, I'm really not sure, I'm not very familiar with Uptrace or Helm. The whole config section is just copied into the config map, if helm has the ability to make substitutions in that content, that might work, but I don't know if that's possible. Sorry I'm not more helpful.

**Comment by vmihailenco** [comment]
I've changed the chart to use static name for ClickHouse that does not depend on the release name: `uptrace-clickhouse`. Hopefully this helps.
