### ISSUE TITLE
Auto restart pods after config update

### ISSUE THREAD

**Issue by xvilo** [uptrace/helm-charts#23]
When the config values get updated, the pod won't restart. This is because the file has changed, but Kubernetes has no direct idea what to reload/restart. 

We can hash the contents of the config file, and add this has as a label. When this changes, Kubernetes will reschedule a new pod properly. I created this issue for reference for now, might create a PR later 👍

**Comment by vmihailenco** [comment]
Sounds like a nice idea. A PR would be be appreciated...

**Comment by xvilo** [comment]
Excuses moi, that was already there https://github.com/uptrace/helm-charts/blob/master/charts/uptrace/templates/uptrace-statefulset.yaml#L20. Not sure why it didnt auto restart yesterday, but it does now....
