### ISSUE TITLE
podAnnotations from values.yaml are not included in uptrace statefulset

### ISSUE THREAD

**Issue by sando38** [uptrace/helm-charts#24]
Hello there,

once I define `podAnnotations` in the values.yaml configuration file, they are not included in the uptrace statefulset. 

Is this on purpose or a bug?

Thanks in advance and have a great day!
Saarko

**Comment by vmihailenco** [comment]
Probably just an overlook. Should be fixed by https://github.com/uptrace/helm-charts/commit/7bdee74501cf20ad08cc1adcac04ff38585acbdd
