### ISSUE TITLE
404 on readiness and liveness probes

### ISSUE THREAD

**Issue by mderazon** [uptrace/helm-charts#25]
service logs are showing 404 when k8s is trying to access readiness and liveness probes on root path `/` :
https://github.com/uptrace/helm-charts/blob/0a8d3c9564f3e7ede27e08822771964942e13146/charts/uptrace/templates/uptrace-statefulset.yaml#L50-L57

This has has started once upgraded from `v1.5.7` to `v1.6.1`.
I tried looking into what have changed since, only thing that looks like might be relevant is this commit
https://github.com/uptrace/uptrace/commit/41d7471dd60e3db91824d1b623a960f3dc1aa861

(I am mounting uptrace under a prefix, but I don't think it should matter as that is external and k8s probes are calling the service internally)

But I am not sure

**Comment by vmihailenco** [comment]
Do you have a local Uptrace config? If so, you might need to fix attribute names (service.name -> service_name) following the example from this [commit](https://github.com/uptrace/helm-charts/commit/533812d43267b95622aae30e3123ead3fa4fbca3).

**Comment by mderazon** [comment]
Thanks, already updated the attribute names, but it did not solve the 404. Any other change could have caused this ?

**Comment by vmihailenco** [comment]
This should be fixed by https://github.com/uptrace/helm-charts/commit/65a698dbb2c7ee337c0cfd454659dfdcede901c7

**Comment by mderazon** [comment]
Confirm that it's fixed, thanks!
