### ISSUE TITLE
Allow to define service annotations to be used with external load balancers as alternative to ingress

### ISSUE THREAD

**Issue by alexandrujieanu** [uptrace/helm-charts#3]
Hello,

I am deploying uptrace on AWS EKS and providing external access using the AWS LB Controller which requires a set of service `metadata.annotations` to detect it and provision the LB.

It would be useful if the helm chart supported it.

Thanks.

**Comment by vmihailenco** [comment]
Hey,

Would be glad to help, but I barely understand the half of what you just said :) If it is not too much trouble, consider sending a PR.

**Comment by vmihailenco** [comment]
@alexandrujieanu thanks :+1: Could you please take a look at https://github.com/uptrace/helm-charts/pull/5? Any other hints we should add to the docs?
