### ISSUE TITLE
expanding ${env:K8S_NODE_NAME}, expected convertable to string value type, got %!q(<nil>)(<nil>) - sidecar otc-container

### ISSUE THREAD

**Issue by radoen** [uptrace/helm-charts#30]
Hello as in #27  I got 
`2024/02/08 09:13:45 collector server run finished with error: failed to resolve config: cannot resolve the configuration: expanding ${env:K8S_NODE_NAME}, expected convertable to string value type, got %!q(<nil>)(<nil>)`

it's not the first time and in the past because I were in testing I simply reinstalled all and it came back to work but now I'm in prod and I cant reinstall it.

I inserted in my override yaml 

```
otelcol:
  enabled: true
```

and upgraded the installation via helm but still stuck.

any ideas?

**Comment by radoen** [comment]
ping

**Comment by vmihailenco** [comment]
No ideas how to fix it, but [this](https://github.com/uptrace/helm-charts/blob/master/charts/uptrace/values.yaml#L122-L126) is how the env variable is defined. It should just contain the K8s node name for Otel Collector.

If you don't need an Otel Collector, you can disable it [here](https://github.com/uptrace/helm-charts/blob/master/charts/uptrace/values.yaml#L33).

**Comment by vmihailenco** [comment]
Closing since this is not actionable.

**Comment by GDXbsv** [comment]
https://github.com/uptrace/helm-charts/pull/42
