### ISSUE TITLE
Remove default value for `image.tag`

### ISSUE THREAD

**Issue by comsma** [uptrace/helm-charts#40]
In `charts/uptrace/values.yaml` the field image.tag is set as seen below.

```yaml
image:
  tag: '1.7.0'
```

this causes the issue of not using the appVersion field from the `charts/uptrace/Chart.yaml` file.

I would suggest setting the image.tag = "" to use the charts appVersion by default.

As of chart version "1.7.4" with an appVersion of "1.7.4" the uptrace image that is being used is "1.7.0" instead of "1.7.4"

**Comment by vmihailenco** [comment]
I've removed the tag in the master branch.
