### ISSUE TITLE
Template improvement

### ISSUE THREAD

**Issue by RaSerge** [uptrace/helm-charts#9]
I review your templates and found. that uptrace ports are hardcoded for statefulset, service. If i redefine them from default 14318 and 14318 in config everything broken.
[in StatefulSet manifest](https://github.com/uptrace/helm-charts/blob/master/charts/uptrace/templates/uptrace-statefulset.yaml#L42)
[in Service maninifest](https://github.com/uptrace/helm-charts/blob/master/charts/uptrace/templates/service.yaml#L16)
What do you thing about using that code for StatefulSet manifest:
```
          ports:
            {{- range $k, $v := .Values.uptrace.config.listen }}
            - name: {{ $k }}
              containerPort: {{ (splitList ":" $v.addr ) | last }}
              protocol: TCP
            {{- end }}

```

**Comment by vmihailenco** [comment]
It makes sense. @alexandrujieanu any objections here?

**Comment by vmihailenco** [comment]
@alexandrujieanu @RaSerge I've sent https://github.com/uptrace/helm-charts/pull/10 with your suggestions. PTAL
